<Project>
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <Import Project="$(SolutionDir)Directory.Build.props" />
  <ItemGroup>
    <PackageReference Include="Shouldly" Version="4.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5" PrivateAssets="All" />
    <ProjectReference Include="..\..\Quorum.CoreWF.Runtime\Quorum.CoreWF.Runtime.csproj" />
  </ItemGroup>
</Project>