<Project>
	<PropertyGroup>
		<Version>6.0.0</Version>
		<RoslynPackageVersion>4.13.0-3.24620.4</RoslynPackageVersion>
		<WarningsAsErrors>true</WarningsAsErrors>
	</PropertyGroup>
	<ItemGroup Condition="$(AssemblyName) != 'Quorum.CoreWF.Xaml'">
		<ProjectReference Include="$(SolutionDir)\Quorum.CoreWF.Xaml\Quorum.CoreWF.Xaml.csproj" PrivateAssets="All" />
	</ItemGroup>
</Project>